### ISSUE TITLE
CorsaroNero butter provider?

### ISSUE THREAD

**Issue by dcampogiani** [raffaeleguidi/corsaronero#1]
I was thinking about write a project butter provider using corsaroNero then I saw this library.

Since I am a Java developer (I've worked just a little bit in the past with node) and you know node and how to use corsaroNero data, any chance you could write the provider?

Here an example: https://github.com/butterproject/butter-provider

**Comment by raffaeleguidi** [comment]
Uhm I have a dramatic lack of free time problem, but... is the project fully usable?

**Comment by dcampogiani** [comment]
Yes.

Popcorntime it's a fork of project butter, the provider will work with the popcorntime client https://github.com/popcorn-official/
